### ISSUE TITLE
Whisper API

### ISSUE THREAD

**Issue by khaledhazime** [robofeiathome/speech_recognition#2]
Test OpenAI's whisper API on speech recognition

- [ ] Add Whisper model to the recognition module
- [ ] Test with common questions
- [ ] Add which model to use as an argument
- [x] Create docker or conda environment for development in zotac

**Comment by luca-moraes** [comment]
conseguimos fazer a gavação e a reprodução do audio, usamos a lib soundevice como alternativa para resolver os erros, agora precisamos integrar isso com a api do whisper fornecida pela lib do speechrecognition

**Comment by luca-moraes** [comment]
Eu e o @PedroTolardo ainda estamos com problemas, rodando recognize_whisper() pela biblioteca do speechRecognition temos erros relacionados ao torch 

> in recognize_whisper
    import torch
ModuleNotFoundError: No module named 'torch'

Tentando com o recognize_google(), não temos nenhum problema.

Usando diretamente o modulo da openai com import whisper temos problemas relacionado ao modulo ffmpeg

> Traceback (most recent call last):
  File "/home/robofei/miniconda3/envs/speechEnv/lib/python3.10/site-packages/whisper/audio.py", line 42, in load_audio
    ffmpeg.input(file, threads=0)
AttributeError: module 'ffmpeg' has no attribute 'input'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/robofei/Documents/speech_recognition/teste_scripts/Speech_whisper_1", line 23, in <module>
    audio = whisper.load_audio("recording.wav")
  File "/home/robofei/miniconda3/envs/speechEnv/lib/python3.10/site-packages/whisper/audio.py", line 46, in load_audio
    except ffmpeg.Error as e:
AttributeError: module 'ffmpeg' has no attribute 'Error'

Acredito que o erro possa ser relacionado a versão do python que funciona corretamente com as bibliotecas necessárias, vou tentar excluir o env criado no conda e refazer a instalçao, porque aparentemente não tem nenhum erro de lógica no código

Instalação do whisper:
https://github.com/openai/whisper

Dependencias do whisper
https://stackoverflow.com/questions/73842876/fmpeg-has-no-attribute-input
https://stackoverflow.com/questions/54843067/no-module-named-torch

**Comment by khaledhazime** [comment]
> Eu e o @PedroTolardo ainda estamos com problemas, rodando recognize_whisper() pela biblioteca do speechRecognition temos erros relacionados ao torch 
> 
> 
> 
> > in recognize_whisper
> 
>     import torch
> 
> ModuleNotFoundError: No module named 'torch'
> 
> 
> 
> Tentando com o recognize_google(), não temos nenhum problema.
> 
> 
> 
> Usando diretamente o modulo da openai com import whisper temos problemas relacionado ao modulo ffmpeg
> 
> 
> 
> > Traceback (most recent call last):
> 
>   File "/home/robofei/miniconda3/envs/speechEnv/lib/python3.10/site-packages/whisper/audio.py", line 42, in load_audio
> 
>     ffmpeg.input(file, threads=0)
> 
> AttributeError: module 'ffmpeg' has no attribute 'input'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
> 
>   File "/home/robofei/Documents/speech_recognition/teste_scripts/Speech_whisper_1", line 23, in <module>
> 
>     audio = whisper.load_audio("recording.wav")
> 
>   File "/home/robofei/miniconda3/envs/speechEnv/lib/python3.10/site-packages/whisper/audio.py", line 46, in load_audio
> 
>     except ffmpeg.Error as e:
> 
> AttributeError: module 'ffmpeg' has no attribute 'Error'
> 
> 
> 
> Acredito que o erro possa ser relacionado a versão do python que funciona corretamente com as bibliotecas necessárias, vou tentar excluir o env criado no conda e refazer a instalçao, porque aparentemente não tem nenhum erro de lógica no código
> 
> 
> 
> Instalação do whisper:
> 
> https://github.com/openai/whisper
> 
> 
> 
> Dependencias do whisper
> 
> https://stackoverflow.com/questions/73842876/fmpeg-has-no-attribute-input
> 
> https://stackoverflow.com/questions/54843067/no-module-named-torch
> 

@cauansousa ve se consegue ajudar eles com isso?

**Comment by cauansousa** [comment]
Consigo, porém só estou no lab pela manhã. Vou marcar com o @luca-moraes / @PedroTolardo  pra fazermos isso.

**Comment by cauansousa** [comment]
Tinha problemas de versão. E uma das bibliotecas que o whisper chamava tinha que ser instalada manualmente. ```conda install -c conda-forge ffmpeg```

**Comment by luca-moraes** [comment]
Erro relacionado ao ffmpeg foi corrigido pelo grande @cauansousa, removendo toda as versões do python e instalando de novo a versão especifica do ffmpeg que é uma dependencia usada pelo whisper

Referências:
 - https://anaconda.org/conda-forge/ffmpeg-python
 - https://github.com/kkroening/ffmpeg-python/issues/174
 - https://github.com/openai/whisper/discussions/514

**Comment by PedroTolardo** [comment]
Logo após a correção do erro, eu e o @luca-moraes começamos os testes no speech recoginition com o whisper.
Fizemos alguns testes com os modelos small e medium. Nenhum dos modos identificou a palavra "hera" ou algo do tipo e além disso quanto melhor o modo, mais pesado o programa fica e demora mais para transcrever a palavra.
Portanto, na semana do dia 06/03 vamos realizar vários testes com o recognize do speechrecogniton para ver qual API tem o melhor reconhecimento.

**Comment by PedroTolardo** [comment]
A logica para funcionamento do alias esta funcionando usando o modelo do google, com o whisper o modelo está um pouco lento e as vezes não reconhece nenhum texto, precisamos testar um pouco mais com o whisper pela api do speech recog, ou pelo proprio whisper, também vamos melhorar a logica do reconhecimento em plano de fundo usando esse exemplo como base: 

- https://stackoverflow.com/questions/53691128/how-to-start-recording-when-something-is-said-python

**Comment by PedroTolardo** [comment]
Criei mais um programa para o alias pois o outro programa "speech_objeto" do @luca-moraes estava dando erro no qual eu não consegui resolver.
No programa "speech_alias" está identificando "hera" e "dizendo" yes. Logo após reconhece a task que deve ser executada. No programa está reconhecendo a task speech recognition.

**Comment by khaledhazime** [comment]
@PedroTolardo 
Qual erro? Quem pode te ajudar nisso?

**Comment by PedroTolardo** [comment]
Avanços dia 14/03:
No arquivo Speech-alias realizei o aprimoramento do alias proposto pelo @khaledhazime, que consiste em separar o "text" em substrings para identificar o alias "hera".
Durante a semana tentarei colocar o arquivo orientado a objeto e aprimorar e cirar outras funçoes.

**Comment by PedroTolardo** [comment]
Avanços (15/03):
Modifiquei algumas coisas no arquivo Speech_alias pois estava apresentando alguns erros. Junto ao @MaSNogueiraS arrumamos o loop da função "transcribe_audio(audio)" pois estava ocorrendo um erro de "NoneType".
Agora com a correção do erro, o loop, o reconhecimento do alias e o reconhecimento das perguntas já estão funcionando corretamente.

**Comment by PedroTolardo** [comment]
Avanços (17/03):
Comecei a estudar um jeito de responder as perguntas. Iniciei olhando o site que o @khaledhazime  me mandou. Além disso, criei um novo arquivo para modificar, o arquivo é o "Speech_answer".  
Neste site apresenta vários métodos para executar pesquisas no google. No link que o khaled me mandou o código apenas mostra os links para possíveis sites de acordo com a pergunta, sem navegar por ele.
Link do site: https://www.geeksforgeeks.org/performing-google-search-using-python-code/

Olhando mais no site, encontrei um outro tópico que diz sobre pesquisa de texto no google usando o selenium e o pyautogui, uma maneira mais eficaz para navegar no site.
Link do site: https://www.geeksforgeeks.org/text-searching-in-google-using-selenium-in-python/?ref=rp

O problema é que estou caindo em um erro no qual não estou conseguindo resolver.
Erro: selenium.common.exceptions.WebDriverException: Message: 'geckodriver' executable needs to be in PATH.

Vou continuar tentando resolver o erro para testar o código e ver se realmente é eficaz.

**Comment by PedroTolardo** [comment]
Avanços(21/03):
Junto ao @MaSNogueiraS demos início as respostas das perguntas do Speech. Para isso, criamos um novo arquivo chamado "Speech_answer_working.py".
Estamos com algumas melhorias em mente e algumas já estão encaminhadas.
Uma das melhorias seria a filtragem das respostas.

**Comment by PedroTolardo** [comment]
Avanços(22/03):
Junto ao @MaSNogueiraS começamos a reproduzir as respostas em fala. Para isso utilizamos a biblioteca "pyttsx3".
As respostas estão em inglês e feminino, o problema é que estão muito robotizadas. Vou tentar pegar a biblioteca do speech anterior.

**Comment by PedroTolardo** [comment]
Avanços(23/03):
Junto ao @MaSNogueiraS arrumamos a reprodução das repostas em fala. Utilizamos a biblioteca "gTTS" que tem a mesma voz que do google. Não consegui testar no zotac pois não está funcionando a entrada de áudio. Tentei em outro pc também mas não está saindo som. Vou tentar no meu pc em casa.

**Comment by PedroTolardo** [comment]
Avanços(24/03):
Consegui arrumar a reprodução das resposta em fala com a voz do google. Junto ao @MaSNogueiraS conseguimos fazer as respostas pelo "chatgpt". O arquivo que está funcionando é o "Speech_gpt".
Agora vou tentar encontrar um jeito para colocar o whisper para ver se melhora na captação do áudio, já que todos os códigos estão com a api do google.

**Comment by PedroTolardo** [comment]
Avanços (30/03):
Junto ao @MaSNogueiraS conseguimos colocar a api do chat gpt para responder as perguntas.
Agora, a "Hera" consegue responder perguntas no geral.
O arquivo que está funcionando é o "Speech_gpt_working".
Demorei um pouco para comentar pois o outro arquivo "Speech_gpt" deu problema e estava resolvendo até agr. A mundança foi alterar a bash que o @MaSNogueiraS indicou pela api do chat gpt.
